image: docker

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY


build-backend:
  stage: build
  script:
    - docker build -f ./backend/Dockerfile  ./backend
    - docker push "$CI_REGISTRY_IMAGE_BACK"


build-frontend:
  stage: build
  script:
    - docker build -f ./frontend/Dockerfile  ./frontend
    - docker push "$CI_REGISTRY_IMAGE_FRONT"

backend-tests:
  image: docker/compose
  stage: test
  script:
    - docker-compose run --entrypoint "npm run unittest" backend

frontend-tests:
  image: docker/compose
  stage: test
  script:
    - docker-compose run --entrypoint "npm run test" frontend
