image: docker

services:
  - docker:dind

before_script:
  - echo "$CI_REGISTRY_USER" 
  - echo "$CI_REGISTRY_PASSWORD" 
  - echo $CI_REGISTRY
  - echo docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY